apiVersion: v1 #Defines the given LLM (where to download it from, and some args)
kind: ConfigMap
metadata:
  name: llama-settings
data:
  MODEL_URL: "MODEL_URL"
  MODEL_FILE: "MODEL_FILE"
  CTX_SIZE: "2048"