name: ci

on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Run Tests
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Ruff Linter
        run: |
          ruff check .

      - name: Run Tests
        run: |
          echo "Tests running"
